version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-api:
    container_name: nest-api
    restart: always
    build: .  
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - redis:/data

volumes:
  postgres:
    name: nest-db
  redis:
    driver: local